---
- name: "Check NVIDIA GPU drivers"
  raw: "nvidia-smi"
  register: nvidia_smi_check
  failed_when: false
  changed_when: false
  check_mode: false
  environment: {}

- name: "Quit playbooks, if NVIDIA GPU drivers exit."
  fail:
    msg: "NVIDIA GPU drivers is detected in your machines, please uninstall it first."
  changed_when: false
  check_mode: false
  environment: {}
  when:
    - nvidia_smi_check.rc == 0

- name: Install nvidia drivers on ubuntu 16.04
  include_tasks: ubuntu-1604-install-nvidia.yml
  when: ansible_distribution_version == '16.04'

- name: Install nvidia drivers on ubuntu 18.04
  include_tasks: ubuntu-1804-install-nvidia.yml
  when: ansible_distribution_version == '18.04'

- name: create persistenced override dir
  file:
    path: /etc/systemd/system/nvidia-persistenced.service.d/
    state: directory
    recurse: yes

- name: configure persistenced service to turn on persistence mode
  copy:
    src: nvidia-persistenced-override.conf
    dest: /etc/systemd/system/nvidia-persistenced.service.d/override.conf

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable persistenced
  systemd:
    name: nvidia-persistenced
    state: started
    enabled: yes

- name: perform nvidia smi
  shell: nvidia-smi
  args:
    executable: /bin/bash
