# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

cluster-type:
  - k8s

prerequisite:
  - frameworkcontroller
  - postgresql

template-list:
  - database-controller.yaml
  - start.sh

start-script: start.sh
stop-script: stop.sh
delete-script: delete.sh
refresh-script: refresh.sh

deploy-rules:
  - in: pai-master
