---
- name: create docker-openpai in /etc
  file:
    path: /etc/docker-openpai
    state: directory
    recurse: yes

- name: copy nvidia runtime configuration file into /etc/docker-openpai
  copy:
    src: daemon-openpai-nvidia-runtime.json
    dest: /etc/docker-openpai/daemon-openpai.json

- name: Add key
  apt_key:
    url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    state: present
  when:
    - install_run_time

- name: add repo
  get_url:
    url: https://nvidia.github.io/nvidia-container-runtime/ubuntu16.04/nvidia-container-runtime.list
    dest: /etc/apt/sources.list.d/nvidia-container-runtime.list
    mode: 0644
    owner: root
    group: root
  when:
    - install_run_time

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when:
    - install_run_time

- name: install packages
  apt:
    name: nvidia-container-runtime
    state: present
    update_cache: yes
  when:
    - install_run_time

