---
- name: Set Locust Base Dir
  set_fact:
    locust_base_dir: "{{ playbook_dir }}/.locust/"

- name: Generate template files in Locust Base Dir
  template:
    src: remove-locust.sh
    dest: "{{ locust_base_dir }}/remove-locust.sh"
    mode: '0777'

- name: Delete Locust Resouce
  command: "/bin/bash {{ locust_base_dir }}/remove-locust.sh"
