name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docs:
    name: Lint docs
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown==2.6.11
    - name: Lint
      run: |
        python src/utilities/doc_checker.py .

  spelling:
    name: Spelling check
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        curl -L https://git.io/misspell | sudo bash -s -- -b /bin
    - name: Check spelling
      run: |
        rm -rf ./src/watchdog/GOPATH/src/github.com/microsoft/watchdog/vendor/
        misspell -error .
